# Generated by Django 5.1.3 on 2024-11-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('category_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('category_title', models.CharField(max_length=100)),
            ],
        ),
    ]
