# Generated by Django 5.1.3 on 2024-12-06 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0002_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='cthd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='hoadon',
            fields=[
                ('sohd', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nghd', models.DateTimeField()),
                ('trigia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sp',
            fields=[
                ('masp', models.CharField(auto_created=True, max_length=4, primary_key=True, serialize=False)),
                ('tensp', models.CharField(max_length=100)),
                ('dvt', models.CharField(default=1, max_length=30)),
                ('nuocsx', models.CharField(default='China', max_length=100)),
                ('gia', models.IntegerField(default=0)),
                ('hinhanh', models.ImageField(upload_to='images/')),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystore.brands')),
            ],
        ),
        migrations.CreateModel(
            name='useraccount',
            fields=[
                ('user_id', models.CharField(auto_created=True, max_length=4, primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=40)),
                ('ho_ten', models.CharField(default='Nguyen Van A', max_length=40)),
                ('so_dt', models.CharField(blank=True, default=None, max_length=10)),
                ('allow_edit', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='categories',
        ),
        migrations.AddField(
            model_name='cthd',
            name='sohd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystore.hoadon'),
        ),
        migrations.AddField(
            model_name='cthd',
            name='masp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystore.sp'),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystore.useraccount'),
        ),
    ]
