# Generated by Django 5.1.3 on 2024-12-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0003_cthd_hoadon_sp_useraccount_delete_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sp',
            name='hinhanh',
            field=models.ImageField(upload_to=''),
        ),
    ]
