# Generated by Django 5.1.3 on 2024-12-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0005_alter_hoadon_nghd_alter_useraccount_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadon',
            name='sohd',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sp',
            name='masp',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sp',
            name='nuocsx',
            field=models.CharField(default='China', max_length=70),
        ),
    ]
