# Generated by Django 5.1.3 on 2024-12-07 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0006_alter_hoadon_sohd_alter_sp_masp_alter_sp_nuocsx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sp',
            name='hinhanh',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
