# Generated by Django 5.1.3 on 2024-12-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0007_alter_sp_hinhanh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sp',
            name='hinhanh',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
