# Generated by Django 5.1.3 on 2024-12-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0008_alter_sp_hinhanh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sp',
            name='tensp',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
