# Generated by Django 5.1.3 on 2024-12-09 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0010_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mystore.categories'),
        ),
    ]
