# Generated by Django 5.1.3 on 2024-12-09 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0011_sp_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sp',
            name='brand_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mystore.brands'),
        ),
    ]
