# Generated by Django 5.1.3 on 2024-12-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0012_alter_sp_brand_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='allow_edit',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user_name',
            field=models.CharField(default='Unknown', max_length=40, null=True, unique=True),
        ),
    ]
