# Generated by Django 5.1.3 on 2024-12-12 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0014_useraccount_is_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cartitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl', models.PositiveIntegerField(default=0)),
                ('ngay_them', models.DateTimeField(auto_now_add=True)),
                ('sp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystore.sp')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
