# Generated by Django 5.1.3 on 2024-12-12 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0015_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='user_id',
            new_name='user',
        ),
    ]
