# Generated by Django 5.1.3 on 2024-12-13 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0017_delete_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoadon',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='useraccount',
        ),
    ]
